---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true
  client_rb:
    chef_license: accept

  #verifier:
  #name: inspec

platforms:
  - name: ubuntu-18.04
  - name: debian/stretch64


suites:
  - name: default
    run_list:
      - recipe[use_remote_template::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
